version: "3.6"
services:

  website:
    build: .
    image: mynode
    ports:
      - "8080:8080"
    networks:
      frontend:
        ipv4_address: 10.0.0.2
    #working_dir: /app
    #tty: true
    #stdin_open: true
    #command:  "ch && /bin/bash"

  db:
    image: mariadb
    networks:
      frontend:
        ipv4_address: 10.0.0.5
    #restart: always
    tty: true
    stdin_open: true
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks: 
      frontend:
        ipv4_address: 10.0.0.6
    ports:
      - "8081:80"
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

